variables:
- name: SolutionBaseName
  value: prg.DevOps

resources:
  repositories:
  - repository: self
  - repository: prg-devops
    type: github
    name: uncle-sola/prg-devops
    endpoint: 'GitHub (PRG)'
    ref: refs/tags/v1.11.2

pool:
    vmImage: 'windows-latest'

trigger:
  branches:
    include:
    - master
    - dev

pr:
  branches:
    include:
    - master
    - dev


stages:
- template: StageTemplates/RunTests.yml
  parameters:
    AzureSubscription: 'prg (f3b14109-a3de-4f54-9f58-46d891380a7e)'
    Powershell5CodeCoveragePercentage: 38
    PowershellCoreCodeCoveragePercentage: 30

